name: Build Resume PDFs

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.yml'
      - '**.yaml'
      - '**.typ'
      - '**.bib'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest

      - name: Build long resume
        run: typst compile resume.typ resume-long.pdf

      - name: Build short resume
        run: typst compile resume-short.typ resume-short.pdf
        continue-on-error: true  # Don't fail if short version doesn't exist

      - name: Build resume with external config
        run: typst compile resume-with-config.typ resume-config.pdf
        continue-on-error: true  # Don't fail if this version doesn't exist

      - name: Build resume with BibTeX
        run: typst compile resume-with-bibtex.typ resume-bibtex.pdf
        continue-on-error: true  # Don't fail if this version doesn't exist

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdfs
          path: |
            resume-*.pdf
            !resume-with-*.pdf
          retention-days: 90

      - name: Upload all resume variants
        uses: actions/upload-artifact@v4
        with:
          name: all-resume-variants
          path: '*.pdf'
          retention-days: 30

  # Optional: Create a release on tag
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build all resume versions
        run: |
          typst compile resume.typ resume-long.pdf
          [ -f resume-short.typ ] && typst compile resume-short.typ resume-short.pdf || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            resume-*.pdf
          body: |
            ## Resume PDFs

            Generated resume PDFs for ${{ github.ref_name }}

            - `resume-long.pdf`: Full resume with all sections
            - `resume-short.pdf`: Shortened resume (if available)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
