name: Upload Resume to Cloud Storage

# This workflow demonstrates uploading to various cloud providers
# Uncomment and configure the sections you need

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.yml'
      - '**.yaml'
      - '**.typ'
      - '**.bib'
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build resume
        run: |
          typst compile resume.typ resume.pdf
          [ -f resume-short.typ ] && typst compile resume-short.typ resume-short.pdf || true

      # ============================================================================
      # OPTION 1: Upload to AWS S3
      # ============================================================================
      # Uncomment and configure AWS credentials in repository secrets
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      #
      # - name: Upload to S3
      #   run: |
      #     aws s3 cp resume.pdf s3://your-bucket-name/resume.pdf --acl public-read
      #     aws s3 cp resume-short.pdf s3://your-bucket-name/resume-short.pdf --acl public-read || true

      # ============================================================================
      # OPTION 2: Upload to Cloudflare R2
      # ============================================================================
      # Uncomment and configure R2 credentials in repository secrets
      # - name: Upload to Cloudflare R2
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     command: r2 object put your-bucket/resume.pdf --file=resume.pdf

      # ============================================================================
      # OPTION 3: Upload to GitHub Pages
      # ============================================================================
      # Uncomment to deploy to GitHub Pages
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .
      #     publish_branch: gh-pages
      #     keep_files: false
      #     include: '*.pdf'

      # ============================================================================
      # OPTION 4: Upload to Google Drive
      # ============================================================================
      # Uncomment and use rclone with Google Drive credentials
      # - name: Upload to Google Drive
      #   run: |
      #     # Install rclone
      #     curl https://rclone.org/install.sh | sudo bash
      #
      #     # Configure rclone (use secrets for credentials)
      #     echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf
      #
      #     # Upload files
      #     rclone copy resume.pdf remote:your-folder/

      # ============================================================================
      # EXAMPLE: Simple artifact upload (default enabled)
      # ============================================================================
      - name: Upload as GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdfs-${{ github.sha }}
          path: |
            resume.pdf
            resume-short.pdf
          retention-days: 90

      - name: Comment on PR with download link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📄 Resume PDFs have been generated! Download them from the [Actions artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            })
